const DataPesertaIndex = [
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
    {
        'ID' : 1,
        'npm' : 'Test npm',
        'nama' : 'bayu',
        'absen_type' : 'type',
        'unit_kerja' : 'unit_kerja',
        'nama_kapal' : 'nama_kapal',
        'masuk' : Date("Y-m-d H:i:s"),
        'keluar' : Date("Y-m-d H:i:s"),
    },
]

export {
    DataPesertaIndex,
}